### PR TITLE
Fixed bugs related to inability to go to create

### PR DESCRIPTION
**Pull request by irjordan**

### CODE REVIEW

**Comment by irjordan** [comment]
Screen Shot 2023-03-14 at 11 55 16 PM
Screen Shot 2023-03-14 at 11 53 49 PM

**Comment by admangan** [comment]
I dont think this is a correct change. The folder is lowercase assets.

**Review by admangan — CHANGES_REQUESTED** [review]
Need to review. Not sure why your folder is "Assets" vs. "assets".

**Comment by larsenweigle** [comment]
I had the same issue as izzy this isn't on her. If you look at origin main, the directory name is capitalized. Need to put up a pr where the directory name 'Assets' is changed to 'assets'.

**Comment by larsenweigle** [comment]
I guess we could do that on this PR. I would revert the lines back to what they were before and then submit a new version of the pr with only a change to the directory name. @admangan should we be pushing changes to the yarn lock file? This is something I wasn't sure about too.

**Review by larsenweigle — APPROVED** [review]

**Review by admangan — APPROVED** [review]

**Comment by admangan** [comment]
Yes you can push changes to yarn lock ( I think this is where modules and packages are added) so that when you run yarn install it is up to date.

**Pull request merged**
